name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  publish:
    name: Publishing
    runs-on: windows-latest
    steps:
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.1.1
        with:
          version: 0.12.0
      - uses: actions/checkout@v3
      - name: Building
        run: zig.exe build
      - name: Packaging final binary
        shell: bash
        run: |
          cd zig-out/
          RELEASE_NAME=motw
          7z a -tzip $RELEASE_NAME.zip './bin/motw.exe' './lib/motw.dll'
          certutil -hashfile $RELEASE_NAME.zip sha256 | grep -E [A-Fa-f0-9]{64} > $RELEASE_NAME.sha256
      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            zig-out/motw.zip
            zig-out/motw.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          command: publish
