name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: motw
          pull-request-title-pattern: "chore: Release v${version}"
          extra-files: |
            build.zig.zon
